apiVersion: v1
kind: Namespace
metadata:
  name: kubedev-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubedev-controller
  namespace: kubedev-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubedev-controller
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps", "secrets", "persistentvolumeclaims", "namespaces"]
    verbs: ["get", "list", "watch", "create", "patch", "update", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "patch", "update", "delete"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch", "create", "patch", "update", "delete"]
  - apiGroups: ["kubedev.my-project.com"]
    resources: ["kubedevenvironments", "kubedevenvironments/status"]
    verbs: ["get", "list", "watch", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubedev-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubedev-controller
subjects:
  - kind: ServiceAccount
    name: kubedev-controller
    namespace: kubedev-system

